# 总结来说，这个 docker-compose.yml 文件定义了一个包含三个服务的应用程序：app1, app2, 和 app3。

# 构建方式：这三个服务都将使用当前目录下的同一个 Dockerfile 来构建它们各自的 Docker 镜像。
# 行为差异：尽管它们基于同一个 Dockerfile，但通过设置不同的 APP_NAME 环境变量，每个服务在容器内部可以表现出不同的行为（例如，显示不同的应用名称）。
# 访问方式：这三个服务都在容器内部的 3000 端口运行，但它们分别通过宿主机的 3001、3002 和 3003 端口对外提供访问。
version: "3"
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
